"""
scenario_builder.py
===================
Convert observed_sessions.json (output of trace_extractor.py) into a
Scyther SPDL scenario file encoding real LoRaWAN traffic observations.

Usage:
    python scenario_builder.py [observed_sessions.json] [output.spdl]

Encoding decisions:
    - Devices with repeated DevNonce  -> two parallel ED instances with same nonce
      (Scyther finds the Nisynch failure caused by replay)
    - Devices using default AppKey    -> AppKey as known public constant
      (Scyther finds Secret failures on derived keys)
    - Unsolicited JoinAccept          -> models rogue NS sending a JoinAccept
      without a prior JoinReq
    - Normal devices                  -> fresh nonce, standard claims (baseline)
"""

import json
import sys
import os
from datetime import datetime
from pathlib import Path

DEFAULT_APPKEYS = {
    "Semtech":   "2b7e151628aed2a6abf7158809cf4f3c",
    "Milesight": "5572404c696e6b4c6f52613230313823",
}
DEFAULT_APPKEY = DEFAULT_APPKEYS["Semtech"]  # fallback

# ── Attack plugin loader ───────────────────────────────────────────────────────

ATTACKS_DIR = Path(__file__).parent / "attacks"


def load_attacks(attacks_dir: Path | None = None) -> list[dict]:
    """Load all attack definitions from the attacks/ directory.

    Each .json file in attacks/ (not in subdirectories) describes one attack
    type: its anomaly trigger, SPDL template path, and expected Scyther claims.

    Returns a list of attack dicts ordered by filename. Falls back to an empty
    list if the directory does not exist (caller uses hardcoded fallback).
    """
    d = attacks_dir or ATTACKS_DIR
    if not d.exists():
        return []
    attacks = []
    for f in sorted(d.glob("*.json")):
        try:
            with open(f) as fh:
                attacks.append(json.load(fh))
        except Exception as e:
            print(f"[WARN] Could not load attack {f.name}: {e}", file=sys.stderr)
    return attacks


def render_template(template_path: str, attacks_dir: Path | None = None, **kwargs) -> str:
    """Read an SPDL template file and render it with the provided variables.

    Template files use Python str.format() syntax — {var_name} for variables,
    {{ and }} to produce literal { and } in the SPDL output.

    Raises FileNotFoundError if the template is missing.
    """
    d = attacks_dir or ATTACKS_DIR
    full_path = d / template_path
    with open(full_path) as f:
        tpl = f.read()
    return tpl.format(**kwargs)

SPDL_HEADER = """\
# LoRaWAN Observed Scenario — Generated by scenario_builder.py
# Source: {pcap}
# Generated: {timestamp}
#
# This file encodes protocol observations from a real PCAP capture as
# Scyther SPDL scenarios. Each scenario targets a specific security property
# that was potentially violated based on anomalies detected in the traffic.
#
# Run with: scyther <this_file>.spdl

hashfunction appSKey, nwkSKey;

"""

SCENARIO_DEFAULT_KEY = """\
# ─────────────────────────────────────────────────────────────────────────────
# SCENARIO: Default AppKey (device {deveui})
# ─────────────────────────────────────────────────────────────────────────────
# Device uses Semtech default AppKey: {appkey}
# This key is public knowledge. Scyther will show the adversary can:
#   1. Decrypt any JoinAccept (since {appkey_const} is a known constant)
#   2. Recover AppNonce and DevNonce from the decrypted JoinAccept
#   3. Derive AppSKey and NwkSKey independently
# Expected: Secret claims FAIL for appSKey and nwkSKey.

const {appkey_const}: Nonce;  # Public — equals default AppKey {appkey}

protocol DefaultKey{safe_id}(ED{safe_id}, NS{safe_id}) {{

    role ED{safe_id} {{
        fresh DevNonce: Nonce;
        var AppNonce:   Nonce;

        send_1(ED{safe_id}, NS{safe_id},
               ED{safe_id}, NS{safe_id}, DevNonce,
               {{ED{safe_id}, NS{safe_id}, DevNonce}}{appkey_const});

        recv_2(NS{safe_id}, ED{safe_id},
               {{AppNonce, NS{safe_id}}}{appkey_const});

        claim(ED{safe_id}, Alive);
        claim(ED{safe_id}, Nisynch);
        # These WILL FAIL — adversary knows {appkey_const} and can derive:
        claim(ED{safe_id}, Secret, appSKey({appkey_const}, AppNonce, DevNonce));
        claim(ED{safe_id}, Secret, nwkSKey({appkey_const}, AppNonce, DevNonce));
    }}

    role NS{safe_id} {{
        var DevNonce:    Nonce;
        fresh AppNonce:  Nonce;

        recv_1(ED{safe_id}, NS{safe_id},
               ED{safe_id}, NS{safe_id}, DevNonce,
               {{ED{safe_id}, NS{safe_id}, DevNonce}}{appkey_const});

        send_2(NS{safe_id}, ED{safe_id},
               {{AppNonce, NS{safe_id}}}{appkey_const});

        claim(NS{safe_id}, Alive);
        claim(NS{safe_id}, Nisynch);
        claim(NS{safe_id}, Secret, appSKey({appkey_const}, AppNonce, DevNonce));
        claim(NS{safe_id}, Secret, nwkSKey({appkey_const}, AppNonce, DevNonce));
    }}
}}

"""

SCENARIO_REPLAY = """\
# ─────────────────────────────────────────────────────────────────────────────
# SCENARIO: DevNonce Replay (device {deveui}, DevNonce {devnonce})
# ─────────────────────────────────────────────────────────────────────────────
# DevNonce {devnonce} was seen multiple times for this device.
# If the NS does not properly track used DevNonces (as spec requires),
# it may respond to a replayed JoinReq with a new JoinAccept.
# This causes the ED to re-join using a predictable nonce, enabling
# session hijacking or selective DoS.
# Expected: Nisynch FAILS — ED cannot confirm it is talking to the real NS.
#
# Modeled as: two ED sessions sharing the same DevNonce (const).

const devnonce{safe_id}: Nonce;  # Fixed — observed repeated DevNonce {devnonce}

protocol Replay{safe_id}(ED{safe_id}, NS{safe_id}) {{

    role ED{safe_id} {{
        # DevNonce is NOT fresh — it is a fixed constant (the repeated value)
        var AppNonce: Nonce;

        send_1(ED{safe_id}, NS{safe_id},
               ED{safe_id}, NS{safe_id}, devnonce{safe_id},
               {{ED{safe_id}, NS{safe_id}, devnonce{safe_id}}}k(ED{safe_id}, NS{safe_id}));

        recv_2(NS{safe_id}, ED{safe_id},
               {{AppNonce, NS{safe_id}}}k(ED{safe_id}, NS{safe_id}));

        claim(ED{safe_id}, Alive);
        # Nisynch WILL FAIL — adversary can replay this JoinReq at any time
        claim(ED{safe_id}, Nisynch);
        claim(ED{safe_id}, Secret, appSKey(k(ED{safe_id}, NS{safe_id}), AppNonce, devnonce{safe_id}));
        claim(ED{safe_id}, Secret, nwkSKey(k(ED{safe_id}, NS{safe_id}), AppNonce, devnonce{safe_id}));
    }}

    role NS{safe_id} {{
        fresh AppNonce: Nonce;

        recv_1(ED{safe_id}, NS{safe_id},
               ED{safe_id}, NS{safe_id}, devnonce{safe_id},
               {{ED{safe_id}, NS{safe_id}, devnonce{safe_id}}}k(ED{safe_id}, NS{safe_id}));

        send_2(NS{safe_id}, ED{safe_id},
               {{AppNonce, NS{safe_id}}}k(ED{safe_id}, NS{safe_id}));

        claim(NS{safe_id}, Alive);
        claim(NS{safe_id}, Nisynch);
        claim(NS{safe_id}, Secret, appSKey(k(ED{safe_id}, NS{safe_id}), AppNonce, devnonce{safe_id}));
        claim(NS{safe_id}, Secret, nwkSKey(k(ED{safe_id}, NS{safe_id}), AppNonce, devnonce{safe_id}));
    }}
}}

"""

SCENARIO_ROGUE_NS = """\
# ─────────────────────────────────────────────────────────────────────────────
# SCENARIO: Rogue NS / Unsolicited JoinAccept (frame {frame})
# ─────────────────────────────────────────────────────────────────────────────
# A JoinAccept was observed with no matching JoinReq in the capture.
# This could indicate a rogue NS or MITM that sent a JoinAccept to force
# a device to re-join under the adversary's chosen session keys.
# This is the canonical LoRaWAN 1.0 Nisynch failure.
# Expected: Nisynch FAILS on ED role.

protocol RogueNSframe{frame}(EDrogue, NSrogue) {{

    role EDrogue {{
        fresh DevNonce: Nonce;
        var AppNonce:   Nonce;

        send_1(EDrogue, NSrogue,
               EDrogue, NSrogue, DevNonce,
               {{EDrogue, NSrogue, DevNonce}}k(EDrogue, NSrogue));

        # ED receives JoinAccept — but cannot verify it came from the real NS
        recv_2(NSrogue, EDrogue,
               {{AppNonce, NSrogue}}k(EDrogue, NSrogue));

        claim(EDrogue, Alive);
        # FAILS: adversary can forge this message in LoRaWAN 1.0
        claim(EDrogue, Nisynch);
        claim(EDrogue, Secret, appSKey(k(EDrogue, NSrogue), AppNonce, DevNonce));
        claim(EDrogue, Secret, nwkSKey(k(EDrogue, NSrogue), AppNonce, DevNonce));
    }}

    role NSrogue {{
        var DevNonce:    Nonce;
        fresh AppNonce:  Nonce;

        recv_1(EDrogue, NSrogue,
               EDrogue, NSrogue, DevNonce,
               {{EDrogue, NSrogue, DevNonce}}k(EDrogue, NSrogue));

        send_2(NSrogue, EDrogue,
               {{AppNonce, NSrogue}}k(EDrogue, NSrogue));

        claim(NSrogue, Alive);
        claim(NSrogue, Nisynch);
    }}
}}

"""

SCENARIO_DATA_REPLAY = """\
# ─────────────────────────────────────────────────────────────────────────────
# SCENARIO: Data Frame Replay (DevAddr {devaddr})
# ─────────────────────────────────────────────────────────────────────────────
# FCnt anomaly detected: {anomaly_type}
# This DevAddr transmitted frames with a non-monotonic or repeated frame counter.
# In LoRaWAN, a receiver MUST reject any uplink with FCnt <= last accepted value.
# If the receiver fails this check, replayed frames are accepted.
#
# Modeled as: FCnt is a fixed constant (not fresh), representing either:
#   - fcnt_decrease: counter went backwards (device reset or rollback attack)
#   - fcnt_repeat:   same counter value used twice (exact replay)
# Either case allows an adversary to replay a captured frame indefinitely.
#
# Grounded in real traffic: FCnt anomaly detected in observed PCAP for
# DevAddr {devaddr} (from {pcap}).
#
# Expected Scyther finding:
#   - Nisynch FAILS on Receiver: adversary replays fixed-FCnt message;
#     two Receiver sessions complete against the same captured message.
#   - Secret on Payload: HOLDS symbolically (session key not leaked);
#     NOTE: In practice, AES-CTR keystream reuse leaks payload differences —
#     this is not expressible in Scyther's symbolic model.

const frozenFCnt{safe_id}: Nonce;  # Fixed FCnt — anomaly type: {anomaly_type}

protocol DataReplay{safe_id}(Sender{safe_id}, Receiver{safe_id}) {{

    role Sender{safe_id} {{
        fresh Payload: Nonce;

        # Uplink with frozen (non-fresh) FCnt — replay-vulnerable
        send_1(Sender{safe_id}, Receiver{safe_id},
               {{Payload}}k(Sender{safe_id}, Receiver{safe_id}),
               frozenFCnt{safe_id});

        claim(Sender{safe_id}, Secret, Payload);
    }}

    role Receiver{safe_id} {{
        var Payload: Nonce;

        recv_1(Sender{safe_id}, Receiver{safe_id},
               {{Payload}}k(Sender{safe_id}, Receiver{safe_id}),
               frozenFCnt{safe_id});

        # FAILS: adversary replays the fixed-FCnt message from a prior capture.
        # Receiver cannot distinguish a fresh uplink from a replay.
        claim(Receiver{safe_id}, Nisynch);
    }}
}}

"""

SCENARIO_BASELINE = """\
# ─────────────────────────────────────────────────────────────────────────────
# SCENARIO: Baseline Normal Device (device {deveui})
# ─────────────────────────────────────────────────────────────────────────────
# Normal OTAA join with fresh nonces and no anomalies detected.
# This models the ideal protocol execution.
# Expected in LoRaWAN 1.0: Nisynch FAILS on ED (protocol design flaw).
# Expected in LoRaWAN 1.1: all claims hold.

protocol Baseline{safe_id}(ED{safe_id}, NS{safe_id}) {{

    role ED{safe_id} {{
        fresh DevNonce: Nonce;
        var AppNonce:   Nonce;

        send_1(ED{safe_id}, NS{safe_id},
               ED{safe_id}, NS{safe_id}, DevNonce,
               {{ED{safe_id}, NS{safe_id}, DevNonce}}k(ED{safe_id}, NS{safe_id}));

        recv_2(NS{safe_id}, ED{safe_id},
               {{AppNonce, NS{safe_id}}}k(ED{safe_id}, NS{safe_id}));

        claim(ED{safe_id}, Alive);
        claim(ED{safe_id}, Nisynch);
        claim(ED{safe_id}, Secret, appSKey(k(ED{safe_id}, NS{safe_id}), AppNonce, DevNonce));
        claim(ED{safe_id}, Secret, nwkSKey(k(ED{safe_id}, NS{safe_id}), AppNonce, DevNonce));
    }}

    role NS{safe_id} {{
        var DevNonce:    Nonce;
        fresh AppNonce:  Nonce;

        recv_1(ED{safe_id}, NS{safe_id},
               ED{safe_id}, NS{safe_id}, DevNonce,
               {{ED{safe_id}, NS{safe_id}, DevNonce}}k(ED{safe_id}, NS{safe_id}));

        send_2(NS{safe_id}, ED{safe_id},
               {{AppNonce, NS{safe_id}}}k(ED{safe_id}, NS{safe_id}));

        claim(NS{safe_id}, Alive);
        claim(NS{safe_id}, Nisynch);
        claim(NS{safe_id}, Secret, appSKey(k(ED{safe_id}, NS{safe_id}), AppNonce, DevNonce));
        claim(NS{safe_id}, Secret, nwkSKey(k(ED{safe_id}, NS{safe_id}), AppNonce, DevNonce));
    }}
}}

"""


def safe_id(deveui: str) -> str:
    """Convert a DevEUI to a valid Scyther SPDL identifier (no underscores)."""
    return "dev" + deveui.replace(":", "").replace("-", "")[:16]


def safe_devaddr(devaddr: str) -> str:
    """Convert a DevAddr hex string to a valid Scyther SPDL identifier."""
    clean = devaddr.replace("0x", "").replace(":", "").replace("-", "")
    return "addr" + clean[:8]


def build_spdl(sessions: dict, attacks_dir: Path | None = None) -> str:
    """Build the full SPDL file from observed sessions.

    If attacks/ directory exists, attack templates are loaded from there.
    Otherwise falls back to the hardcoded SCENARIO_* string constants above.
    """
    pcap = sessions.get("pcap", "unknown.pcap")
    devices = sessions.get("devices", {})
    anomalies = sessions.get("anomalies", [])

    # Load attack definitions (empty list = use hardcoded fallback below)
    _attacks = load_attacks(attacks_dir)
    _use_plugins = bool(_attacks)

    parts = [SPDL_HEADER.format(
        pcap=pcap,
        timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    )]

    # Track which device EUIs have already been handled
    handled = set()
    baseline_count = 0
    scenario_count = 0

    # Collect anomaly types per device / devaddr
    replay_anomalies = {}     # deveui -> devnonce
    rogue_ns_frames = []
    fcnt_anomalies = {}       # devaddr -> anomaly_type (first occurrence only)

    for a in anomalies:
        if a["type"] == "DevNonce_Replay":
            deveui = a.get("deveui", "unknown")
            if deveui not in replay_anomalies:
                replay_anomalies[deveui] = a.get("devnonce", "0000")
        elif a["type"] == "Unsolicited_JoinAccept":
            rogue_ns_frames.append(a.get("frame", 0))
        elif a["type"] in ("FCnt_fcnt_decrease", "FCnt_fcnt_repeat"):
            devaddr = a.get("devaddr", "unknown")
            if devaddr not in fcnt_anomalies:
                fcnt_anomalies[devaddr] = a["type"]

    # ── Helpers that emit one scenario block ──────────────────────────────────

    def _emit(template_name: str, hardcoded: str, **kwargs) -> str:
        """Render via plugin template if available, else use hardcoded string."""
        if _use_plugins:
            try:
                return render_template(template_name, attacks_dir, **kwargs)
            except Exception as e:
                print(f"[WARN] Template {template_name} failed ({e}), using built-in",
                      file=sys.stderr)
        return hardcoded.format(**kwargs)

    # ── Build scenarios for each device ───────────────────────────────────────
    for deveui, device in devices.items():
        if deveui.startswith("devaddr:"):
            continue  # Skip data-only devices (no join observed)
        if not device.get("join_attempts"):
            continue  # Skip devices with no join data

        sid = safe_id(deveui)
        if sid in handled:
            continue
        handled.add(sid)

        if device.get("uses_default_key"):
            parts.append(_emit(
                "templates/default_key.spdl", SCENARIO_DEFAULT_KEY,
                deveui=deveui,
                appkey=device.get("detected_appkey", DEFAULT_APPKEY),
                appkey_const=f"defaultAppKey{sid}",
                safe_id=sid,
            ))
            scenario_count += 1

        elif deveui in replay_anomalies:
            parts.append(_emit(
                "templates/devnonce_replay.spdl", SCENARIO_REPLAY,
                deveui=deveui,
                devnonce=replay_anomalies[deveui],
                safe_id=sid,
            ))
            scenario_count += 1

        else:
            # Normal device — baseline scenario
            if baseline_count < 3:  # Limit baseline scenarios (they're all the same)
                parts.append(_emit(
                    "templates/baseline.spdl", SCENARIO_BASELINE,
                    deveui=deveui,
                    safe_id=sid,
                ))
                baseline_count += 1

    # ── Add rogue NS scenarios ─────────────────────────────────────────────────
    for frame in rogue_ns_frames[:2]:  # At most 2 rogue NS scenarios
        parts.append(_emit("templates/rogue_ns.spdl", SCENARIO_ROGUE_NS, frame=frame))
        scenario_count += 1

    # ── Add data frame replay scenarios (FCnt anomalies) ──────────────────────
    data_replay_count = 0
    for devaddr, anomaly_type in fcnt_anomalies.items():
        if data_replay_count >= 3:  # Limit to 3 data replay scenarios
            break
        sid = safe_devaddr(devaddr)
        if sid in handled:
            continue
        handled.add(sid)
        parts.append(_emit(
            "templates/fcnt_replay.spdl", SCENARIO_DATA_REPLAY,
            devaddr=devaddr,
            anomaly_type=anomaly_type,
            pcap=pcap,
            safe_id=sid,
        ))
        scenario_count += 1
        data_replay_count += 1

    # If no specific anomalies found, add one baseline to show the protocol design flaw
    if scenario_count == 0 and baseline_count == 0:
        parts.append(_emit(
            "templates/baseline.spdl", SCENARIO_BASELINE,
            deveui="no_anomalies_found",
            safe_id="devbaseline",
        ))

    return "".join(parts)


def main():
    input_path  = sys.argv[1] if len(sys.argv) > 1 else "observed_sessions.json"
    output_path = sys.argv[2] if len(sys.argv) > 2 else "models/scyther/observed_scenario.spdl"

    if not os.path.exists(input_path):
        print(f"[ERROR] Input file not found: {input_path}", file=sys.stderr)
        sys.exit(1)

    with open(input_path) as f:
        sessions = json.load(f)

    spdl = build_spdl(sessions)

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(spdl)

    scenario_types = {
        "Baseline": spdl.count("protocol Baseline"),
        "Replay (DevNonce)": spdl.count("protocol Replay"),
        "RogueNS": spdl.count("protocol RogueNS"),
        "DefaultKey": spdl.count("protocol DefaultKey"),
        "DataReplay (FCnt)": spdl.count("protocol DataReplay"),
    }
    print(f"[+] SPDL scenario written to {output_path}")
    print(f"    Scenarios generated:")
    for name, count in scenario_types.items():
        if count:
            print(f"      {name}: {count}")
    print(f"    Run: scyther {output_path}")


if __name__ == "__main__":
    main()
